export const UPDATE_USERS_LIST = 'UPDATE_USERS_LIST';
export const REQUEST_USERS_LIST = 'REQUEST_USERS_LIST';
export const DELETE_USER = 'DELETE_USER'
export const EDIT_USER = 'EDIT_USER';
export const CREATE_USER = 'CREATE_USER';
export const REQUEST_SINGLE_USER = 'REQUEST_SINGLE_USER';
export const UPDATE_SINGLE_USER = 'UPDATE_SINGLE_USER';